secretGenerator:
  - name: db-creds
    options: 
      labels: 
        app-config: my-config  
    literals:
      - username=postgres
      - password=password1

  - name: domain-name
    literals:
      - domain=api.kodekloud.com


configMapGenerator:
  - name: keycloak-config
    literals:
      - http-port=80
      - https-port=443
  - name: nginx-config
    files:
      - nginx.conf

